package edu.univ.erp.util;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;

public class PDFUtil {
    public static boolean exportToPDF(ResultSet rs, String username, String filePath) {
        Document doc = new Document(PageSize.A4);
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(filePath));
            doc.open();
            Font titleFont = new Font(Font.HELVETICA, 18, Font.BOLD);
            Paragraph title = new Paragraph("University ERP - Official Transcript", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            doc.add(title);
            doc.add(new Paragraph("\nStudent: " + username));
            doc.add(new Paragraph("Date Generated: " +
                    new SimpleDateFormat("dd MMM yyyy, HH:mm").format(new Date())));
            doc.add(new Paragraph("\n"));
            PdfPTable table = new PdfPTable(4);
            table.setWidthPercentage(100);
            table.setWidths(new float[]{2, 4, 2, 2});
            String[] headers = {"Course Code", "Course Title", "Final Score", "Final Grade"};
            for (String header : headers) {
                PdfPCell c = new PdfPCell(new Phrase(header, new Font(Font.HELVETICA, 12, Font.BOLD)));
                c.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(c);
            }
            while (rs.next()) {
                table.addCell(rs.getString("code"));
                table.addCell(rs.getString("title"));
                table.addCell(rs.getString("final_score"));
                table.addCell(rs.getString("final_grade"));
            }
            doc.add(table);
            doc.add(new Paragraph("\nGenerated by University ERP System" +
                    new SimpleDateFormat("yyyy").format(new Date())));
            doc.close();
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        } finally {
            doc.close();
        }
    }
}
